# Metadata
title: Kit France
repository: makendon/kits-dna
email:
description:
tagline: My personal website # SEO field
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kitfrance.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
linkedin_username: kit-france-a1a3b874
github_username: makendon
author: Kit France # Global author to replace need for front matter
logo: /assets/images/C.jpeg/ # SEO field

# Google Analyics
google_analytics:

# GitHub link settings
github:
  is_project_page: true
  repository_name: kits-dna
  repository_url: https://github.com/makendon/kits-dna
  owner_name: makendon
  owner_url: https://github.com/makendon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# Header
header_pages:
  - about.md
  - projects.md
  - blog.md

#Permalink
permalink: pretty

# Blogging
show_excerpts: true

# Images
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Markdown
markdown: GFM
