# Lychee link checker configuration
# https://lychee.cli.rs/usage/configuration/

exclude = [
    'localhost:4000',  # Jekyll server example
    'http://localhost:8080/pagefind/pagefind-ui.css'  # Unclear why .css in exclude_path doesn't exclude this error
]

# Exclude paths
exclude_path = [
    'node_modules',
    '\.css$',
    '\.xml$'
]

# Comma-separated list of accepted status codes for valid links
accept = [
    "200",
    "429",
    "999"
]
