name: cSpell CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cspell:
    name: Spell Check
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.6.0

      - name: Install dependencies
        run: npm ci

      - name: Run cSpell
        run: npx cspell-cli "**/*.md" "!LICENSE.md" --no-progress --gitignore
