name: Vale CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
        with:
          vale_flags: "--glob=!LICENSE.md --minAlertLevel=error"
